export const languageList = [
  {name: 'Mandarin Chinese', langCode: 'zh-CN'},
  {name: 'Spanish', langCode: 'es-ES'},
  {name: 'English', langCode: 'en-GB'},
  {name: 'Hindi', langCode: 'hi-IN'},
  {name: 'Arabic', langCode: 'ar-SA'},
  {name: 'Bengali', langCode: 'bn-BD'},
  {name: 'Portuguese', langCode: 'pt-PT'},
  {name: 'Russian', langCode: 'ru-RU'},
  {name: 'French', langCode: 'fr-FR'},
  {name: 'German', langCode: 'de-DE'},
  {name: 'Urdu', langCode: 'ur-PK'},
  {name: 'Japanese', langCode: 'ja-JP'},
  {name: 'Tamil', langCode: 'ta-IN'},
];

type TranslatedPhrases = {
  [key: string]: string;
};

export const getLangCode = (language: string): string =>
  languageList.filter(l => l.name === language)[0].langCode;

export const translatedPhrases: TranslatedPhrases = {
  'Mandarin Chinese': '让我们用中文说话!',
  Spanish: 'Hablemos en español!',
  English: "Let's speak in English!",
  Hindi: 'हम हिंदी में बात करें!',
  Arabic: '!دعونا نتحدث بالعربية',
  Bengali: 'আসলে আমরা বাঙালি কথা বলতে চাই!',
  Portuguese: 'Vamos falar em português!',
  Russian: 'Давайте говорить по-русски!',
  French: 'Parlons en français!',
  German: 'Lass uns auf Deutsch sprechen!',
  Urdu: '!ہم اردو میں بات کریں',
  Japanese: '日本語で話しましょう！',
  Tamil: 'தமிழில் பேச வேண்டும்!',
};

export interface SamplePhrase {
  name: string;
  samplePhrases: string[];
}
export const samplePhrases: SamplePhrase[] = [
  {
    name: 'Mandarin Chinese',
    samplePhrases: [
      '欢迎光临！很高兴见到你。请随便坐，我们有很多好东西要聊。',
      '你好！欢迎来到这里，我们可以聊聊天，分享一些有趣的故事。',
      '请进，请坐！欢迎来到这个温馨的地方，我们可以一起聊天，分享生活。',
      '你好吗？',
      '你现在在做什么？',
      '你最喜欢的爱好是什么？',
      '最近去过哪里旅行了吗？',
      '你最喜欢的中餐是什么？',
      '请告诉我你最后读过或看过的书或电影。',
      '周末有什么计划吗？',
      '你喜欢运动吗？如果是，你最喜欢的运动是什么？',
      '你空闲时是如何度过的？',
      '目前有令人兴奋的项目吗？',
      '你最喜欢的地方是哪里？',
      '你有中国音乐的推荐吗？',
      '你最喜欢的季节是什么，为什么？',
      '有没有有趣的故事想分享？',
      '你如何描述你的理想一天？',
    ],
  },
  {
    name: 'Spanish',
    samplePhrases: [
      '¡Bienvenido! Qué alegría tenerte aquí. ¿Cómo ha sido tu día? ¿Quieres hablar de algo en particular?',
      'Hola, ¿cómo estás? Estoy encantado de darte la bienvenida. ¿Te apetece charlar un rato?',
      'Te damos la bienvenida a este espacio acogedor. ¿Qué te trae por aquí?',
      '¿Cómo estás?',
      '¿Qué haces últimamente?',
      '¿Cuáles son tus pasatiempos favoritos?',
      '¿Has viajado recientemente?',
      '¿Cuál es tu plato favorito de la cocina española?',
      'Háblame sobre tu último libro/película favorita.',
      '¿Cuáles son tus planes para el fin de semana?',
      '¿Te gusta el deporte? Si es así, ¿cuál es tu deporte favorito?',
      '¿Cómo ocupas tu tiempo libre?',
      '¿Tienes proyectos emocionantes en este momento?',
      '¿Cuál es tu lugar favorito en España?',
      '¿Tienes recomendaciones de música española?',
      '¿Cuál es tu temporada favorita y por qué?',
      '¿Tienes alguna anécdota interesante para compartir?',
      '¿Cómo describirías tu día ideal?',
    ],
  },
  {
    name: 'English',
    samplePhrases: [
      "Welcome! It's a pleasure to have you here. How has your day been so far? Anything exciting on your mind?",
      "Hello there! Welcome to our little corner. What brings you here today? Let's have a chat!",
      "Greetings! Step into our world. I'm eager to hear about your day. What's the latest in your world?",
    ],
  },
  {
    name: 'Hindi',
    samplePhrases: [
      'स्वागत है! बहुत खुशी हुई कि तुम यहाँ हो. तुम्हारे दिन कैसा था? कुछ खास बातें सुनने को मिलेंगी?',
      'नमस्ते! तुम्हारा स्वागत है. कैसा चल रहा है? कोई खास बातें बताओ.',
      'आपका स्वागत है! बैठिए, राहत करें. आपके साथ बातचीत करने का इंतजार है.',
      'कैसे हो तुम?',
      'तुम अभी क्या कर रहे हो?',
      'तुम्हारा पसंदीदा शौक क्या है?',
      'क्या तुमने हाल ही में कहीं यात्रा की है?',
      'तुम्हारी पसंदीदा हिंदी खाने की वस्तु क्या है?',
      'मुझे अपने पिछले पसंदीदा पुस्तक/फिल्म के बारे में बताओ.',
      'वीकेंड के लिए तुम्हारी क्या योजनाएँ हैं?',
      'क्या तुम्हें खेलना पसंद है? अगर हां, तो तुम्हारा पसंदीदा खेल क्या है?',
      'तुम फ्री टाइम में कैसे व्यतीत करते हो?',
      'क्या तुम्हारे पास इस समय को लेकर कोई रोमांचक परियोजना है?',
      'तुम्हारी सबसे पसंदीदा जगह क्या है?',
      'तुम्हारे पास हिंदी संगीत के लिए कोई सिफारिश है?',
      'तुम्हारा पसंदीदा मौसम कौन सा है और क्यों?',
      'तुम्हारे पास कोई दिलचस्प किस्सा है जो तुम शेयर कर सकते हो?',
      'तुम अपने परिपूर्ण दिन को कैसे वर्णन करोगे?',
    ],
  },
  {
    name: 'Arabic',
    samplePhrases: [
      'أهلاً وسهلاً! نورت المكان. كيف كان يومك؟ هل ترغب في بداية محادثة؟',
      'مرحبًا! كيف حالك؟ راضون بوجودك. هل تريد الدخول في محادثة؟',
      'أهلاً بك! استمتع بالراحة. هل ترغب في مناقشة أمور معينة؟',
      'كيف حالك؟',
      'ما الذي تفعله حالياً؟',
      'ما هي هواياتك المفضلة؟',
      'هل سافرت مؤخرًا؟',
      'ما هو طبقك المفضل من المأكولات العربية؟',
      'حدثني عن كتابك/فيلمك المفضل الأخير.',
      'ما هي خططك لعطلة نهاية الأسبوع؟',
      'هل تحب الرياضة؟ إذا كان الأمر كذلك، ما هو الرياضة المفضلة لديك؟',
      'كيف تقضي وقت فراغك؟',
      'هل لديك مشاريع مثيرة في الوقت الحالي؟',
      'ما هو مكانك المفضل في العالم العربي؟',
      'هل لديك توصيات للموسيقى العربية؟',
      'ما هو موسمك المفضل ولماذا؟',
      'هل لديك قصة مثيرة لتشاركها؟',
      'كيف توصف يومك المثالي؟',
    ],
  },
  {
    name: 'Bengali',
    samplePhrases: [
      'স্বাগতম! আমরা এখানে আপনাকে স্বাগত জানাই। কেমন আছেন? কি কি আপনির কাছে সহজে যায় তা শেয়ার করতে পারি?',
      'নমস্কার! আমরা আপনাকে এখানে আমন্ত্রিত করছি। আপনি যে কিছু নিয়ে কথা বলতে চান তা জানতে চানি।',
      'আপনাকে এখানে স্বাগত জানাই। আমরা এখানে থাকতে খুব খুশি। কী বার্তা আছে তোমার?',
    ],
  },
  {
    name: 'Portuguese',
    samplePhrases: [
      'Como você está?',
      'O que você está fazendo agora?',
      'Qual é o seu hobby favorito?',
      'Você viajou recentemente?',
      'Qual é o seu prato favorito da culinária portuguesa?',
      'Conte-me sobre o seu último livro/filme favorito.',
      'Você tem planos para o fim de semana?',
      'Você gosta de esportes? Se sim, qual é o seu esporte favorito?',
      'Como você passa o seu tempo livre?',
      'Existem projetos emocionantes no momento?',
      'Qual é o seu lugar favorito?',
      'Você tem recomendações de música portuguesa?',
      'Qual é a sua estação do ano favorita e por quê?',
      'Tem alguma história interessante para compartilhar?',
      'Como você descreveria o seu dia ideal?',
    ],
  },
  {
    name: 'Russian',
    samplePhrases: [
      'Добро пожаловать! Рады видеть вас. Как прошел ваш день? Есть что-то, о чем вы хотели бы поговорить?',
      'Привет, как у вас дела? Добро пожаловать в наш уголок. Есть что-то интересное на вашем уме?',
      'Рады приветствовать вас в этом уютном месте. Расскажите, как у вас дела?',
      'Как вы себя чувствуете?',
      'Что вы делаете сейчас?',
      'Какое ваше любимое хобби?',
      'Вы недавно путешествовали?',
      'Какое ваше любимое блюдо русской кухни?',
      'Расскажите мне о вашей последней любимой книге/фильме.',
      'У вас есть планы на выходные?',
      'Любите ли вы спорт? Если да, то какой ваш любимый вид спорта?',
      'Как вы проводите свободное время?',
      'Есть ли у вас в настоящее время интересные проекты?',
      'Какое ваше любимое место?',
      'У вас есть рекомендации по русской музыке?',
      'Какое ваше любимое время года и почему?',
      'Есть ли у вас интересные истории для рассказа?',
      'Как бы вы описали ваш идеальный день?',
    ],
  },
  {
    name: 'French',
    samplePhrases: [
      'Bienvenue! Des nouvelles à partager?',
      "Qu'est-ce qui vous amène aujourd'hui?",
      'Quoi de neuf?',
      'Comment ça va?',
      "Qu'est-ce que tu fais de beau en ce moment?",
      'Quels sont tes passe-temps préférés?',
      'As-tu voyagé récemment?',
      'Quel est ton plat préféré de la cuisine française?',
      'Parle-moi de ton dernier livre/film préféré.',
      'Quels sont tes projets pour le week-end?',
      'Est-ce que tu aimes le sport? Si oui, quel est ton sport préféré?',
      'Comment tu occupes ton temps libre?',
      'As-tu des projets passionnants en ce moment?',
      'Quel est ton endroit préféré en France?',
      'Tu as des recommandations de musique française?',
      'Quelle est ta saison préférée et pourquoi?',
      'As-tu une anecdote intéressante à partager?',
      'Comment tu décrirais ta journée idéale?',
    ],
  },
  {
    name: 'German',
    samplePhrases: [
      'Wie geht es dir?',
      'Was machst du gerade?',
      'Was ist dein Lieblingshobby?',
      'Warst du in letzter Zeit auf Reisen?',
      'Was ist dein Lieblingsgericht aus der deutschen Küche?',
      'Erzähl mir etwas über dein letztes Lieblingsbuch/Film.',
      'Hast du Pläne für das Wochenende?',
      'Magst du Sport? Wenn ja, welcher ist dein Lieblingssport?',
      'Wie verbringst du deine Freizeit?',
      'Gibt es derzeit aufregende Projekte?',
      'Was ist dein Lieblingsort?',
      'Hast du Empfehlungen für deutsche Musik?',
      'Welche Jahreszeit magst du am liebsten und warum?',
      'Hast du eine interessante Geschichte zum Teilen?',
      'Wie würdest du deinen perfekten Tag beschreiben?',
    ],
  },
  {
    name: 'Urdu',
    samplePhrases: [
      'خوش آمدید! یہاں ہونا خوشی کی بات ہے۔ آپکا دن کیسا رہا؟ کچھ خاص باتیں سننے کے لئے مجہ سے بات چیت کریں۔',
      'ہیلو، کیسے ہیں؟ آپکا خوش آمدید ہے. کیا آپ کچھ دیر گپ شپ کریں گے؟',
      'آپکا خوش آمدید ہے! بیٹھیے، آرام کریں. آپ کے دن کی باتیں سننے کا شوق ہے.',
      'آپ اب کیا کر رہے ہیں؟',
      'آپ کا مشغلہ کیا ہے؟',
      'کیا آپ نے حال ہی میں کہی گھوما؟',
      'آپ کا مقامی کھانے کا پسندیدہ ڈش کیا ہے؟',
      'میرے پسندیدہ کتاب/فلم کے بارے میں بتائیں.',
      'آپ کا ہفتے کا خصوصی منصوبہ کیا ہے؟',
      'کیا آپ کو کھیلنا پسند ہے؟ اگر ہاں، تو آپ کا پسندیدہ کھیل کیا ہے؟',
      'آپ اپنا فری ٹائم کیسے گزارتے ہیں؟',
      'کیا آپ کے پاس اس وقت کو لے کر کوئی دلچسپ منصوبہ ہے؟',
      'آپ کی مقامی محبوب جگہ کیا ہے؟',
      'کیا آپ کے پاس اردو موسیقی کے لیے کوئی تجویز ہے؟',
      'آپ کا پسندیدہ موسم کون سا ہے اور کیوں؟',
      'آپ کے پاس کوئی دلچسپ قصہ ہے جو آپ شیئر کر سکتے ہیں؟',
      'آپ اپنے مکمل دن کو کیسے وصف کریں گے؟',
    ],
  },
  {
    name: 'Japanese',
    samplePhrases: [
      'ようこそ！お会いできて嬉しいです。どうぞお座りください、たくさんお話ししましょう。',
      'こんにちは！こちらへようこそ。一緒にお話しできて嬉しいです。',
      'お越しいただきありがとうございます。どうぞおくつろぎください。一緒におしゃべりしましょう。',
      'お元気ですか？',
      '今何をしていますか？',
      'お気に入りの趣味は何ですか？',
      '最近どこか旅行に行きましたか？',
      'お気に入りの日本料理は何ですか？',
      '最後に読んだ本や観た映画について教えてください。',
      '週末の予定はありますか？',
      'スポーツはお好きですか？もしそうなら、お気に入りのスポーツは何ですか？',
      '暇な時間はどのように過ごしますか？',
      '現在のエキサイティングなプロジェクトはありますか？',
      'お気に入りの場所はどこですか？',
      '日本の音楽のおすすめはありますか？',
      'お気に入りの季節は何で、なぜですか？',
      '共有したい面白いエピソードはありますか？',
      '理想的な一日をどのように描きますか？',
    ],
  },
  {
    name: 'Tamil',
    samplePhrases: [
      'ஏன் இருக்கிறீர்கள்?',
      'நீங்கள் இன்று என்ன செய்கிறீர்கள்?',
      'உங்கள் பிடித்த முகப்புக்குக் கேட்கின்றேன்.',
      'நீங்கள் குடும்பத்தின் முதல் சகாரத்தை கேட்கிறேன்.',
      'உங்களுக்கு பிடித்த தமிழ் உணர்வு என்ன?',
      'உங்கள் கடினமான படம் / நூல் பற்றி எனக்கு சொல்லுங்கள்.',
      'இந்த வாரம் உங்களுக்கு என்ன திட்டமிடப்பட்டுள்ளது?',
      'உங்களுக்கு விளையாட விரும்பும் விளையாட்டு என்ன?',
      'உங்கள் இருக்கை காலத்தில் நீங்கள் என்ன செய்கிறீர்கள்?',
      'உங்களுக்கு ரசிகரான திட்டம் உள்ளதுன்னு சொல்லுங்கள்.',
      'உங்களுக்கு இன்னும் உள்ள செய்தியாளர் உண்டா?',
      'உங்களுக்கு பிடித்த இடம் எது?',
      'நீங்கள் எந்த இனத்தின் இனத்தை விரும்புகிறீர்கள்?',
      'உங்களுக்கு ஆரோக்கியமான உலகம் என்ன?',
      'உங்களுக்கு உணர்வுகள் உள்ளனவா? அவை என்ன?',
      'உங்களுக்கு ஏன் அருகிலுள்ளவர்களுக்கு உடனே சொந்தமாக உண்டு உள்ளது?',
    ],
  },
];
